"""
services/calendar_gen.py
────────────────────────
DAS (Days After Sowing) based crop activity schedule generator.
Negative DAS = pre-sowing activities.
DAS 0 = sowing day.

Event types:
  Land Preparation | Sowing | Irrigation | Fertilizer
  Pest Monitoring  | Disease Monitoring | Harvest | Post-Harvest
  Nursery | Thinning / Gap Filling | Weeding | Spray
"""
from __future__ import annotations
from datetime import date, timedelta
from typing import List, Dict, Any

# ─── DAS schedule tables ─────────────────────────────────────────────────────
# Each entry: (das, event_type, title, description)

CROP_SCHEDULES: Dict[str, List[tuple]] = {
    "Rice": [
        (-14, "Land Preparation",  "Deep Ploughing & Field Leveling",   "Plough 2–3 times, level the field, and repair bunds."),
        (-7,  "Land Preparation",  "Puddling & Nursery Bed Preparation","Puddle the main field; prepare raised nursery beds for sowing."),
        (0,   "Nursery",           "Nursery Sowing",                    "Sow pre-germinated seeds in nursery @ 25–30 kg/ha rate."),
        (7,   "Irrigation",        "Nursery Irrigation Check",          "Maintain 2–3 cm standing water in nursery beds."),
        (14,  "Pest Monitoring",   "Nursery Pest Scouting",             "Check for leaf roller, gall midge, and root aphids in nursery."),
        (21,  "Sowing",            "Transplanting to Main Field",       "Transplant 20–21 day old seedlings at 20×20 cm spacing."),
        (25,  "Fertilizer",        "Basal Fertilizer — DAP + MOP",      "Apply DAP @ 60 kg/ha and MOP @ 40 kg/ha as basal dose."),
        (28,  "Irrigation",        "First Flood Irrigation",            "Maintain 5 cm standing water for 5–7 days post-transplanting."),
        (35,  "Weeding",           "First Weeding / Pre-emergence",     "Apply pre-emergence herbicide (Butachlor) or manual weeding."),
        (40,  "Fertilizer",        "First Nitrogen Dose (1/3 Urea)",    "Apply 40 kg Urea/ha at active tillering stage."),
        (45,  "Pest Monitoring",   "Stem Borer & BPH Scouting",         "Check for stem borer dead hearts and BPH infestation (ETL: 10 BPH/hill)."),
        (55,  "Irrigation",        "Irrigation — Panicle Initiation",   "Maintain water depth at 5 cm at panicle initiation stage."),
        (60,  "Fertilizer",        "Second Nitrogen Dose (1/3 Urea)",   "Apply 40 kg Urea/ha at panicle initiation stage."),
        (65,  "Disease Monitoring","Blast & Sheath Blight Scouting",    "Check for leaf blast lesions (diamond-shaped grey spots) and sheath blight."),
        (70,  "Spray",             "Fungicide Spray if needed",         "If blast detected, apply Tricyclazole 75WP @ 0.6 kg/ha."),
        (80,  "Fertilizer",        "Third Nitrogen Dose (1/3 Urea)",    "Apply remaining 40 kg Urea/ha at heading/flowering stage."),
        (85,  "Irrigation",        "Flowering Stage Irrigation",        "Critical — maintain 5 cm water during flowering for good grain set."),
        (90,  "Pest Monitoring",   "Leaf Folder & Neck Borer Check",    "Inspect for leaf folder damage and neck borer at boot stage."),
        (100, "Disease Monitoring","False Smut & Brown Spot Check",     "Check for false smut balls and brown spot lesions."),
        (110, "Irrigation",        "Pre-harvest Drainage",              "Drain field 10–15 days before harvest for field drying."),
        (120, "Harvest",           "Crop Harvest",                      "Harvest when 80% grains turn golden yellow. Moisture: 20–22%."),
        (125, "Post-Harvest",      "Threshing & Cleaning",              "Thresh within 1–2 days of harvesting. Clean and grade grain."),
        (130, "Post-Harvest",      "Drying & Storage",                  "Sun-dry to 14% moisture before storage in gunny bags."),
        (140, "Post-Harvest",      "Straw Management",                  "Mulch straw or incorporate into soil. Avoid burning."),
    ],
    "Wheat": [
        (-14, "Land Preparation",  "Deep Ploughing (Zaid / Post-Kharif)","Plough 2–3 times post-Kharif harvest. Remove stubble and level field."),
        (-7,  "Land Preparation",  "Field Leveling & Bed Preparation",  "Laser level the field; make beds or flat sowing layout."),
        (0,   "Sowing",            "Wheat Sowing (Seed Drill)",          "Sow at 100 kg seeds/ha in rows 22 cm apart at 5 cm depth."),
        (5,   "Irrigation",        "Pre-emergence Irrigation (Life Water)","Apply light life-giving irrigation immediately after sowing."),
        (21,  "Irrigation",        "Crown Root Initiation (CRI) Irrigation","Critical first irrigation at 20–21 DAS. Determines final yield."),
        (25,  "Fertilizer",        "First Nitrogen Dose (1/3 Urea)",    "Top-dress 43 kg Urea/ha after CRI irrigation."),
        (40,  "Irrigation",        "Second Irrigation — Tillering",     "Irrigate at maximum tillering stage."),
        (45,  "Weeding",           "Herbicide Application",             "Apply Isoproturon 75WP @ 1.25 kg/ha for narrow-leaf weeds."),
        (55,  "Pest Monitoring",   "Aphid & Jassid Scouting",          "Check aphid population on flag leaf. ETL: 5 aphids/tiller."),
        (60,  "Irrigation",        "Third Irrigation — Jointing",       "Irrigate at jointing / stem elongation stage."),
        (65,  "Fertilizer",        "Second Nitrogen Dose (1/3 Urea)",   "Top-dress second dose of Urea @ 43 kg/ha."),
        (75,  "Disease Monitoring","Yellow Rust / Brown Rust Scouting", "Check lower leaves for orange/yellow pustules (rust)."),
        (78,  "Irrigation",        "Fourth Irrigation — Booting",       "Irrigate at boot stage (flag leaf emergence)."),
        (80,  "Spray",             "Fungicide Spray if Rust Detected",  "Apply Propiconazole 25EC @ 0.5 L/ha if rust incidence >5%."),
        (90,  "Irrigation",        "Fifth Irrigation — Heading",        "Irrigate at ear emergence / heading stage."),
        (95,  "Fertilizer",        "Third Nitrogen Dose (1/3 Urea)",    "Apply remaining 43 kg Urea/ha."),
        (105, "Irrigation",        "Sixth Irrigation — Grain Fill",     "Last irrigation at milky/dough stage for grain plumpness."),
        (115, "Disease Monitoring","Loose Smut & Karnal Bunt Check",    "Inspect ears for loose smut smelly masses and karnal bunt."),
        (120, "Irrigation",        "Seventh Irrigation (if needed)",    "Optional — at hard dough stage only if soil moisture is low."),
        (130, "Harvest",           "Crop Harvest — Combine / Manual",   "Harvest at 12–14% grain moisture. Use combine harvester."),
        (135, "Post-Harvest",      "Threshing, Cleaning & Bagging",     "Clean, grade, and bag in gunny sacks."),
        (140, "Post-Harvest",      "Drying & Mandi Transport",          "Sun dry to 12% moisture. Grade and transport to mandi."),
    ],
    "Cotton": [
        (-21, "Land Preparation",  "Deep Ploughing & Ridging",          "Plough 30–45 cm deep. Form ridges and furrows."),
        (-7,  "Land Preparation",  "Pre-sowing Irrigation (Tav)",       "Apply pre-sowing irrigation. Prepare raised bed planting."),
        (0,   "Sowing",            "Bt Cotton Sowing",                  "Sow Bt Cotton seeds at 0.75 kg/ha in 90×60 cm spacing."),
        (10,  "Irrigation",        "First Irrigation",                  "Apply life irrigation if rains are insufficient."),
        (20,  "Thinning",          "Thinning & Gap Filling",            "Keep one healthy plant per hill. Fill gaps within 15 DAS."),
        (25,  "Fertilizer",        "Basal Fertilizer — SSP + MOP",      "Apply SSP @ 250 kg/ha and MOP @ 60 kg/ha."),
        (35,  "Weeding",           "First Weeding / Hoeing",            "Inter-row cultivation + hand weeding to 30 DAS."),
        (40,  "Fertilizer",        "First Nitrogen Dose (1/2 Urea)",    "Top-dress 65 kg Urea/ha at squaring stage."),
        (45,  "Pest Monitoring",   "Aphid & Thrips Scouting",          "Check for sucking pest colonies on undersides of leaves."),
        (55,  "Irrigation",        "Square Stage Irrigation",           "Irrigate at squaring/boll formation stage."),
        (60,  "Disease Monitoring","Bacterial Blight & Leaf Curl Check","Inspect for angular water-soaked lesions and leaf curl virus."),
        (65,  "Fertilizer",        "Second Nitrogen Dose (1/2 Urea)",   "Apply remaining 65 kg Urea/ha at boll development."),
        (70,  "Pest Monitoring",   "Pink Bollworm & American Bollworm", "Monitor pheromone trap catches. >8 moths/trap/week = spray."),
        (80,  "Irrigation",        "Boll Development Irrigation",       "Regular irrigation every 10–12 days during boll fill."),
        (90,  "Spray",             "Bollworm Spray if needed",          "Apply Profenofos 50EC @ 1L/ha if economic threshold crossed."),
        (100, "Disease Monitoring","Grey Mildew & Alternaria Leaf Spot","Inspect for powdery spots on older leaves."),
        (120, "Pest Monitoring",   "Spotted Bollworm & Boll Weevil",   "Final pest check before boll opening."),
        (140, "Harvest",           "First Cotton Picking",              "Pick fully opened lockered bolls. Avoid rain-damaged bolls."),
        (160, "Harvest",           "Second Cotton Picking",             "Second round of picking. Grade fibre quality."),
        (180, "Post-Harvest",      "Stalk Destruction",                 "Uproot stalks within 15 days of final harvest to break pest cycle."),
    ],
    "Tomato": [
        (-35, "Nursery",           "Nursery Bed Preparation & Seeding", "Prepare raised nursery beds. Sow seeds @ 350–400g/ha. Cover with mulch."),
        (-21, "Nursery",           "Nursery Irrigation & Damping Control","Water gently twice daily. Apply Thiram drench for damping off."),
        (-7,  "Land Preparation",  "Transplant Bed Preparation",        "Apply FYM 20 t/ha. Form raised beds or ridges."),
        (0,   "Sowing",            "Transplanting (35-day-old seedlings)","Transplant hardened seedlings at 60×45 cm spacing in evening."),
        (5,   "Irrigation",        "Post-transplant Drip Setup",        "Activate drip system. Apply 4 L water/plant/day initially."),
        (10,  "Fertilizer",        "Starter Fertilizer (NPK 19:19:19)", "Apply 200 kg NPK 19:19:19/ha via drip/soil."),
        (20,  "Weeding",           "First Weeding & Mulch Laying",      "Apply black/silver mulch film. Weed manually around plants."),
        (25,  "Pest Monitoring",   "Whitefly & Thrips Scouting",       "Check underside of leaves. ETL: 10 whitefly/leaf."),
        (30,  "Fertilizer",        "Second Fertilizer — Calcium Nitrate","Apply Ca Nitrate @ 100 kg/ha via drip for blossom end rot prevention."),
        (35,  "Irrigation",        "Irrigation Adjustment — Flowering", "Increase to 6 L/plant/day. Avoid over-irrigation at flowering."),
        (40,  "Disease Monitoring","Early Blight & Late Blight Scouting","Check for concentric ring spots (early blight) and water-soaked lesions."),
        (42,  "Spray",             "Preventive Fungicide Spray",        "Apply Mancozeb 75WP @ 2.5 kg/ha as protective spray."),
        (50,  "Thinning",          "Staking & Pruning (indeterminate)", "Stake plants with bamboo. Remove suckers and bottom leaves."),
        (55,  "Fertilizer",        "High-K Fertilizer (NPK 0:52:34)",   "Shift to 0:52:34 @ 80 kg/ha for fruit set and quality."),
        (60,  "Pest Monitoring",   "Fruit Borer Scouting",              "Check for Helicoverpa bore holes in fruits. ETL: 1 larva/plant."),
        (65,  "Irrigation",        "Fruit Fill Irrigation",             "Maintain consistent soil moisture. Avoid water stress at fruit fill."),
        (70,  "Disease Monitoring","Septoria Leaf Spot & ToBRFV Check", "Inspect for circular necrotic spots and viral mosaic symptoms."),
        (80,  "Spray",             "Foliar Micronutrient Spray",        "Apply Boron + Zinc mix @ 2 kg/ha for fruit quality."),
        (85,  "Harvest",           "First Harvest (Breaker Stage)",     "Harvest at breaker/pink stage for distant markets (30–40% colour)."),
        (95,  "Harvest",           "Subsequent Pickings (every 3–4 days)","Continue picking every 3–4 days at mature green to red stage."),
        (115, "Post-Harvest",      "Grading, Packing & Transport",      "Grade by size and colour. Pack in ventilated boxes/crates."),
        (120, "Post-Harvest",      "Field Sanitation",                  "Remove crop debris, diseased plants. Prepare for next crop."),
    ],
    "Potato": [
        (-14, "Land Preparation",  "Deep Ploughing & FYM Application",  "Plough 30 cm deep. Apply FYM @ 25 t/ha and mix well."),
        (-7,  "Land Preparation",  "Ridge and Furrow Formation",         "Form ridges at 60 cm apart. Apply basal fertilizer."),
        (0,   "Sowing",            "Seed Tuber Planting",                "Plant certified seed tubers @ 2500 kg/ha in furrows at 5–7 cm depth."),
        (5,   "Irrigation",        "Pre-emergence Irrigation",           "Light irrigation to maintain soil moisture for germination."),
        (10,  "Irrigation",        "Emergence Check & Gap Filling",      "Fill missing spots within 10 days. Apply light irrigation."),
        (20,  "Weeding",           "First Earthing-Up & Weeding",        "Pull soil up to stems. Remove weeds manually/mechanically."),
        (25,  "Fertilizer",        "First Nitrogen Dose (Urea)",         "Apply half the Urea dose (50 kg/ha) after first earthing-up."),
        (35,  "Disease Monitoring","Early Blight Monitoring",            "Check older leaves for concentric target-ring lesions."),
        (40,  "Weeding",           "Second Earthing-Up",                 "Final earthing-up to prevent greening of tubers."),
        (45,  "Pest Monitoring",   "Aphid & Cutworm Scouting",          "Monitor for aphid colonies (virus vector). ETL: 5 aphids/plant."),
        (50,  "Fertilizer",        "Second Nitrogen Dose (Urea)",        "Apply remaining 50 kg Urea/ha. Avoid N after 55 DAS."),
        (55,  "Disease Monitoring","Late Blight Monitoring (Critical!)", "Check underside of leaves for white sporulation. Spray immediately."),
        (58,  "Spray",             "Late Blight Emergency Spray",        "Apply Metalaxyl-M + Mancozeb @ 2.5 kg/ha at first sign."),
        (65,  "Irrigation",        "Tuber Bulking Irrigation",           "Critical period — maintain field capacity. Irrigate every 7 days."),
        (75,  "Pest Monitoring",   "Black Scurf & Sclerotia Check",     "Monitor for Rhizoctonia black scurf on emerging shoots."),
        (85,  "Irrigation",        "Final Irrigation",                   "Last irrigation at 85–90 DAS. Allow soil to dry before harvest."),
        (90,  "Post-Harvest",      "Haulm Cutting (Desiccation)",        "Cut vines 10–14 days before harvest to toughen skin."),
        (100, "Harvest",           "Potato Harvest",                     "Harvest when foliage dies (100–110 DAS). Avoid damage."),
        (105, "Post-Harvest",      "Curing & Sorting",                   "Cure at 15–20°C for 10–14 days. Sort by size and quality."),
        (115, "Post-Harvest",      "Cold Storage / Mandi Transport",     "Store at 4°C with 90–95% RH, or transport to mandi."),
    ],
    "Mustard": [
        (-14, "Land Preparation",  "Field Preparation & Stubble Removal","Remove previous crop stubble. Plough and level field."),
        (-7,  "Land Preparation",  "Pre-sowing Irrigation (if needed)", "Apply pre-sowing irrigation. Prepare fine tilth seedbed."),
        (0,   "Sowing",            "Mustard Sowing (Zero-till Drill)",  "Sow 5 kg seeds/ha in rows 30–45 cm apart using zero-till drill."),
        (10,  "Thinning",          "Thinning & Gap Filling",            "Thin to maintain plant-to-plant distance of 10–15 cm."),
        (20,  "Fertilizer",        "First Nitrogen Dose (1/2 Urea)",    "Apply 40 kg Urea/ha at 20 DAS."),
        (25,  "Irrigation",        "First Irrigation — Pre-flowering",  "Apply first irrigation at rosette/branching stage."),
        (30,  "Weeding",           "Weeding / Pendimethalin Application","Apply Pendimethalin 30EC as pre-emergence or manual weeding."),
        (40,  "Pest Monitoring",   "Aphid Scouting (Critical Stage!)",  "Check terminal shoots for aphid colonies. ETL: 30 aphids/plant."),
        (42,  "Fertilizer",        "Second Nitrogen Dose (1/2 Urea)",   "Apply remaining 40 kg Urea/ha at flowering initiation."),
        (45,  "Irrigation",        "Second Irrigation — Flowering",     "Apply at 50% flowering stage. Critical for yield."),
        (50,  "Spray",             "Aphid Control Spray",               "Apply Imidacloprid 17.8SL @ 0.25 L/ha if ETL crossed."),
        (55,  "Disease Monitoring","Alternaria Blight & Sclerotinia",  "Check for dark concentric spots on leaves and white mold on stem."),
        (60,  "Irrigation",        "Third Irrigation — Pod Fill",       "Critical for pod development and seed size."),
        (70,  "Pest Monitoring",   "Painted Bug & Sawfly Monitoring",   "Check for adults on pods. ETL: 1 bug/10 pods."),
        (85,  "Harvest",           "Mustard Harvest",                   "Harvest when 75–80% pods turn golden yellow. Cut in early morning."),
        (90,  "Post-Harvest",      "Threshing & Winnowing",             "Thresh after 2–3 days of field drying. Winnow to clean seed."),
        (95,  "Post-Harvest",      "Oil Seed Drying & Storage",         "Dry to 8% moisture. Store in gunny bags in cool dry place."),
    ],
    "Corn": [
        (-14, "Land Preparation",  "Deep Ploughing & FYM Application",  "Plough deeply. Apply FYM @ 10 t/ha and mix well."),
        (-7,  "Land Preparation",  "Harrowing & Bed Formation",         "Fine till, form ridges at 60 cm spacing."),
        (0,   "Sowing",            "Maize/Corn Sowing",                 "Sow 20 kg seeds/ha at 60×25 cm spacing, 3–5 cm depth."),
        (7,   "Irrigation",        "Pre-emergence Irrigation",           "Light irrigation if rainfall is insufficient."),
        (15,  "Thinning",          "Thinning to One Plant per Hill",    "Remove weak seedlings. Keep the strongest plant per hill."),
        (20,  "Weeding",           "First Weeding / Atrazine Spray",    "Apply Atrazine 50WP @ 2 kg/ha as pre-emergence."),
        (25,  "Fertilizer",        "First Nitrogen (1/4 Urea)",         "Apply 45 kg Urea/ha at V4–V5 leaf stage."),
        (30,  "Irrigation",        "Knee-high Stage Irrigation",        "Irrigate at knee-high stage (30–35 DAS)."),
        (40,  "Pest Monitoring",   "Fall Army Worm Scouting (FAW)",     "Check youngest leaf for egg masses and feeding damage. Critical!"),
        (45,  "Fertilizer",        "Second Nitrogen (1/4 Urea)",        "Apply 45 kg Urea/ha at V8 stage."),
        (50,  "Spray",             "FAW Spray if Detected",             "Apply Emamectin benzoate 5SG @ 0.4 g/L in leaf whorl."),
        (55,  "Irrigation",        "Tasseling Irrigation",              "Critical — irrigate at tasseling / silk emergence."),
        (60,  "Fertilizer",        "Third Nitrogen (1/4 Urea)",         "Apply 45 kg Urea/ha at tasseling stage."),
        (65,  "Disease Monitoring","Turcicum Leaf Blight & Smut Check", "Inspect for cigar-shaped lesions and smut galls on ears."),
        (70,  "Irrigation",        "Grain Fill Irrigation",             "Maintain moisture at blister and milk stage."),
        (80,  "Fertilizer",        "Fourth Nitrogen (1/4 Urea)",        "Final topdress of 45 kg Urea/ha at milk stage."),
        (90,  "Pest Monitoring",   "Ear Borer & Cob Worm Check",        "Check ears for Helicoverpa damage. Treat if >5% ears damaged."),
        (100, "Harvest",           "Green Corn / Sweet Corn Harvest",   "For sweet corn: harvest at milky stage (18–22% moisture)."),
        (115, "Harvest",           "Dry Corn Harvest",                  "For grain corn: harvest at 25–30% moisture. Dry post-harvest."),
        (120, "Post-Harvest",      "Shelling, Drying & Storage",        "Shell, dry to 12% moisture, store in metal bins or gunny bags."),
    ],
    "Sugarcane": [
        (-21, "Land Preparation",  "Deep Subsoiling & Trench Marking",  "Subsoil to 45–60 cm. Mark trenches at 90 cm spacing."),
        (-7,  "Land Preparation",  "FYM & Basal Fertilizer in Trench",  "Apply FYM 25 t/ha + SSP in trenches."),
        (0,   "Sowing",            "Sett Planting (3-bud setts)",        "Lay 3-bud setts in trenches. Cover with 5 cm soil. @ 7500 setts/ha."),
        (10,  "Irrigation",        "First Irrigation",                  "Life irrigation within 10 days of planting."),
        (20,  "Pest Monitoring",   "Early Shoot Borer Scouting",        "Check for yellowing + dead hearts. Pull test the central leaf."),
        (30,  "Thinning",          "Gap Filling",                       "Fill missing spots with fresh setts or rooted sprouts."),
        (40,  "Fertilizer",        "First Nitrogen Dose (1/3 Urea)",    "Apply 65 kg Urea/ha as first top-dress."),
        (60,  "Irrigation",        "Irrigation Every 10–15 Days",       "Maintain regular irrigation. Critical during grand growth phase."),
        (75,  "Weeding",           "Trash Mulching / Earthing Up",      "Earthing up + mulch with dried trash between rows."),
        (90,  "Fertilizer",        "Second Nitrogen Dose (1/3 Urea)",   "Apply 65 kg Urea/ha at grand growth phase."),
        (100, "Pest Monitoring",   "Top Shoot Borer & Mealybug Check",  "Inspect for top borer damage and mealybug colonies."),
        (120, "Fertilizer",        "Third Nitrogen Dose (1/3 Urea)",    "Apply final 65 kg Urea/ha at 4-month stage."),
        (150, "Disease Monitoring","Red Rot & Smut Disease Scouting",   "Check for red rot (reddening of internodes) and smut whips."),
        (200, "Pest Monitoring",   "Termite & Grub Monitoring",         "Inspect soil around roots for termite galleries."),
        (270, "Irrigation",        "Pre-harvest Water Management",      "Stop irrigation 30–45 days before harvest for higher sucrose."),
        (300, "Harvest",           "Sugarcane Harvest",                 "Harvest when brix is 18–22%. Cut close to ground."),
        (305, "Post-Harvest",      "Transport to Sugar Mill",           "Transport to mill within 24 hours of cutting to prevent sucrose loss."),
        (310, "Post-Harvest",      "Ratoon Management",                 "Remove dead stumps, apply FYM, and manage for ratoon crop."),
    ],
    "Soybean": [
        (-14, "Land Preparation",  "Field Preparation & Lime Application","Deep plough, apply lime if pH < 6. Level field."),
        (-7,  "Land Preparation",  "Seed Bed Preparation",               "Prepare fine tilth. Mark rows at 45 cm spacing."),
        (0,   "Sowing",            "Soybean Sowing with Rhizobium",      "Treat seeds with Rhizobium + PSB. Sow @ 70 kg/ha."),
        (7,   "Irrigation",        "Pre-emergence Irrigation",           "Light irrigation if soil is dry. Avoid waterlogging."),
        (15,  "Weeding",           "Pre-emergence Weedicide",            "Apply Pendimethalin 30EC @ 3 L/ha."),
        (20,  "Thinning",          "Thinning to Stand",                  "Ensure proper plant population (3–4 lakh plants/ha)."),
        (30,  "Fertilizer",        "Micronutrient Application",          "Apply Zinc Sulphate @ 25 kg/ha if deficiency observed."),
        (35,  "Irrigation",        "Flowering Stage Irrigation",         "Irrigate at flowering (R1 stage). Critical period."),
        (40,  "Pest Monitoring",   "Girdle Beetle & Semilooper Scouting","Check for girdled stems and skeletonized leaves."),
        (45,  "Disease Monitoring","Bacterial Pustule & Target Spot",    "Check for raised pustules on undersides of leaves."),
        (50,  "Irrigation",        "Pod Fill Irrigation",                "Irrigate at pod development (R5 stage). Do not skip."),
        (55,  "Spray",             "Hexaconazole Spray for Rust",        "Apply Hexaconazole 5SC @ 1 L/ha if rust symptoms appear."),
        (65,  "Pest Monitoring",   "Pod Borer & Whitefly Check",         "Check pods for bore holes. ETL: 5% pod damage."),
        (90,  "Harvest",           "Soybean Harvest",                    "Harvest when 95% pods turn brown. Moisture: 14–18%."),
        (95,  "Post-Harvest",      "Threshing, Cleaning & Grading",      "Thresh immediately. Clean and grade seed. Check for mould."),
        (100, "Post-Harvest",      "Drying & Storage",                   "Dry to 12% moisture. Store in cool dry aerated place."),
    ],
    "Chickpeas (Gram)": [
        (-14, "Land Preparation",  "Deep Ploughing & FYM Mixing",       "Plough to 25–30 cm. Mix FYM @ 5 t/ha."),
        (-7,  "Land Preparation",  "Seed Bed Preparation",               "Make fine tilth seedbed. Mark rows at 30 cm."),
        (0,   "Sowing",            "Chickpea Sowing with Rhizobium",     "Treat with Rhizobium + PSB inoculant. Sow @ 80 kg/ha."),
        (10,  "Irrigation",        "Pre-emergence Irrigation (Light)",   "If sown in dry conditions, light irrigation at emergence."),
        (20,  "Weeding",           "Hand / Mechanical Weeding",          "Remove weeds before 25 DAS for critical weed-free period."),
        (25,  "Pest Monitoring",   "Cutworm & Aphid Scouting",          "Check soil surface for cutworm damage. ETL: 1 cut/m row."),
        (40,  "Irrigation",        "Flowering Stage Irrigation",         "One critical irrigation at first flower appearance."),
        (45,  "Disease Monitoring","Fusarium Wilt & Collar Rot Check",   "Check for sudden wilting of plants. Pull test for root rot."),
        (55,  "Pest Monitoring",   "Pod Borer (Helicoverpa) Scouting",  "Most damaging pest. Check pods for bore holes. Use ETL cards."),
        (58,  "Spray",             "Pod Borer Bioinsecticide Spray",     "Apply Helicoverpa NPV @ 250 LE/ha + Neem oil if ETL >1 larva/m²."),
        (70,  "Irrigation",        "Pod Fill Irrigation (if Kabuli)",    "Only for Kabuli chickpea — one irrigation at pod fill."),
        (90,  "Harvest",           "Chickpea Harvest",                   "Harvest when 75–80% pods dry brown. Uproot or cut above ground."),
        (95,  "Post-Harvest",      "Drying, Threshing & Grading",        "Sun dry 2–3 days. Thresh, clean and grade seed."),
        (100, "Post-Harvest",      "Storage",                            "Store at <12% moisture with phosphine fumigation if needed."),
    ],
    "Groundnut": [
        (-14, "Land Preparation",  "Deep Ploughing & Gypsum Application","Plough to 25 cm. Apply Gypsum @ 400 kg/ha in root zone."),
        (-7,  "Land Preparation",  "Ridge Formation",                    "Form ridges at 45 cm spacing for well-drained beds."),
        (0,   "Sowing",            "Groundnut Pod Planting",             "Shell pods carefully. Sow at 10 cm spacing @ 120 kg/ha."),
        (7,   "Irrigation",        "Life Irrigation",                    "Apply life irrigation on 7th day."),
        (15,  "Weeding",           "Pre-emergence Herbicide",            "Apply Pendimethalin 30EC @ 2.5 L/ha before emergence."),
        (20,  "Fertilizer",        "Micronutrient — Boron Spray",        "Spray Solubor @ 0.5 kg in 500 L water at peg initiation."),
        (30,  "Irrigation",        "Pegging Stage Irrigation",           "Critical — maintain moisture at pegging (30–40 DAS)."),
        (35,  "Pest Monitoring",   "Leaf Miner & Thrips Scouting",      "Check for mines in leaflets. ETL: 5 mines/leaf."),
        (40,  "Disease Monitoring","Tikka (Leaf Spot) Disease Check",   "Check for tan/dark brown circular spots on leaves."),
        (45,  "Fertilizer",        "Gypsum Application to Peg Zone",    "Apply 200 kg Gypsum/ha to peg zone for calcium supply."),
        (50,  "Irrigation",        "Pod Development Irrigation",         "Regular irrigation every 7–10 days during pod fill."),
        (55,  "Spray",             "Tikka Control Spray",               "Apply Chlorothalonil 75WP @ 2 kg/ha if disease >10% incidence."),
        (65,  "Pest Monitoring",   "White Grub Monitoring",             "Observe for wilting patches. Apply Chlorpyrifos soil drench."),
        (90,  "Harvest",           "Groundnut Harvest",                  "Harvest when 75% pods have dark-coloured mesocarp."),
        (95,  "Post-Harvest",      "Drying & Curing",                    "Sun dry windrows for 4–5 days. Cure before storing."),
        (100, "Post-Harvest",      "Threshing, Grading & Storage",       "Shell, grade and store at <10% moisture."),
    ],
    "Onion": [
        (-42, "Nursery",           "Nursery Bed Preparation & Seeding", "Sow seeds in raised nursery beds @ 8 kg/ha. Cover lightly."),
        (-28, "Nursery",           "Nursery Irrigation & Weeding",      "Water twice daily. Weed nursery beds at 10 and 21 days."),
        (-14, "Land Preparation",  "Main Field Preparation",            "Apply FYM @ 20 t/ha. Prepare raised beds or flat beds."),
        (0,   "Sowing",            "Transplanting (42-day Seedlings)",  "Transplant seedlings at 15×10 cm spacing in the evening."),
        (7,   "Irrigation",        "First Irrigation Post-Transplant",  "Apply light irrigation immediately. Repeat every 3–5 days."),
        (15,  "Fertilizer",        "Basal Fertilizer — SSP + MOP",      "Apply SSP @ 375 kg/ha + MOP @ 100 kg/ha."),
        (20,  "Fertilizer",        "First Nitrogen Dose (1/3 Urea)",    "Apply 37 kg Urea/ha at 20 DAS."),
        (25,  "Weeding",           "First Weeding",                     "Remove weeds. Avoid deep digging near bulb zone."),
        (35,  "Disease Monitoring","Purple Blotch & Stemphylium Check", "Check leaves for violet lesions with yellow halo."),
        (40,  "Fertilizer",        "Second Nitrogen Dose (1/3 Urea)",   "Apply 37 kg Urea/ha at 40 DAS."),
        (45,  "Pest Monitoring",   "Thrips Scouting",                   "Check inner leaf folds for thrips. ETL: 30 thrips/plant."),
        (50,  "Irrigation",        "Bulb Initiation Irrigation",        "Increase frequency at bulb initiation. Avoid water stress."),
        (60,  "Fertilizer",        "Third Nitrogen Dose (1/3 Urea)",    "Apply remaining 37 kg Urea/ha. Last N dose at 60 DAS."),
        (75,  "Irrigation",        "Pre-harvest Water Management",      "Reduce irrigation after 75 DAS to improve bulb dry matter."),
        (90,  "Harvest",           "Onion Harvest (50% Neck Fall)",     "Harvest when 50% of necks have fallen. Uproot carefully."),
        (95,  "Post-Harvest",      "Field Curing (7–10 Days)",          "Leave harvested onions in field for 7–10 days under shade."),
        (105, "Post-Harvest",      "Topping, Grading & Storage",         "Remove tops, grade by size, store in net bags / cold storage."),
    ],
    "Apple": [
        (-30, "Land Preparation",  "Dormant Season Pruning",            "Prune in January–February. Remove dead/crossing branches."),
        (-15, "Spray",             "Dormant Spray (Chlorpyrifos)",      "Apply Chlorpyrifos 20EC @ 1.5 L/ha for scale insects."),
        (0,   "Sowing",            "Bud Break — Season Start",          "Monitor silver tip / green tip bud break. First activity of season."),
        (10,  "Spray",             "Copper Spray at Green Tip",         "Apply Copper Oxychloride @ 3 g/L for canker control."),
        (20,  "Fertilizer",        "Pre-bloom Fertilization",           "Apply NPK 10:26:26 @ 150 kg/ha. FYM @ 20 t/ha in pits."),
        (25,  "Disease Monitoring","Scab Infection Period Watch",        "Predict scab infection using Mills table (temp + wetness hrs)."),
        (30,  "Spray",             "First Scab Spray at Pink",          "Apply Mancozeb 75WP @ 2.5 g/L at tight cluster/pink stage."),
        (40,  "Sowing",            "Full Bloom — Pollination Stage",    "Ensure bee hives in orchard for cross-pollination."),
        (45,  "Spray",             "Second Scab Spray at Petal Fall",   "Apply Captan 50WP @ 2.5 g/L + Mancozeb at petal fall."),
        (55,  "Thinning",          "Chemical Thinning (Fruitlet Stage)","Apply Carbaryl @ 1.5 g/L for fruit thinning (June drop)."),
        (60,  "Fertilizer",        "Calcium Spray (Fruit Quality)",     "Apply Calcium Chloride @ 4 g/L foliar — repeat 3–4 times."),
        (75,  "Pest Monitoring",   "Codling Moth & Aphid Scouting",    "Check pheromone traps for codling moth. Sponge aphid colonies."),
        (90,  "Disease Monitoring","Powdery Mildew Check",              "Inspect shoot tips for white powdery growth."),
        (100, "Spray",             "Third Fungicide Spray",             "Apply Hexaconazole 5SC if scab/mildew pressure continues."),
        (120, "Fertilizer",        "Mid-season Fertilizer (Urea Foliar)","Foliar Urea spray @ 0.5% for fruit size improvement."),
        (150, "Pest Monitoring",   "San Jose Scale & Mite Check",       "Check for scale crawlers and spider mite infestations."),
        (160, "Harvest",           "Pre-harvest Assessment",            "Check fruit colour development and starch-iodine index."),
        (170, "Harvest",           "Apple Harvest (Variety dependent)", "Harvest when 75% colour and starch index ≤5."),
        (180, "Post-Harvest",      "Grading & Packing",                 "Grade by size and colour. Pack in CFB boxes with tissue paper."),
        (185, "Post-Harvest",      "Cold Storage @ 2–4°C",              "Store at 2–4°C with 90–95% RH for 4–6 months."),
    ],
}

# Fallback for crops not in recipes
DEFAULT_SCHEDULE = [
    (-14, "Land Preparation",  "Field Preparation",              "Plough and prepare the field."),
    (0,   "Sowing",            "Sowing / Transplanting",         "Sow seeds or transplant seedlings."),
    (15,  "Irrigation",        "First Irrigation",               "Apply irrigation as needed."),
    (30,  "Fertilizer",        "Basal Fertilizer Application",   "Apply NPK as per soil test recommendation."),
    (45,  "Pest Monitoring",   "First Pest & Disease Scouting",  "Scout for pests and diseases."),
    (60,  "Irrigation",        "Mid-season Irrigation",          "Maintain irrigation schedule."),
    (75,  "Fertilizer",        "Top-dress Fertilizer",           "Apply top-dress nitrogen fertilizer."),
    (90,  "Disease Monitoring","Disease Monitoring",             "Check for fungal and bacterial diseases."),
    (105, "Harvest",           "Harvest",                        "Harvest crop at maturity."),
    (115, "Post-Harvest",      "Post-Harvest Handling",          "Dry, grade and store or transport."),
]

# Event type → color key (used in frontend)
EVENT_TYPE_COLORS = {
    "Land Preparation": "stone",
    "Nursery":          "lime",
    "Sowing":           "green",
    "Thinning":         "emerald",
    "Irrigation":       "blue",
    "Fertilizer":       "amber",
    "Weeding":          "yellow",
    "Pest Monitoring":  "orange",
    "Disease Monitoring":"red",
    "Spray":            "rose",
    "Harvest":          "primary",
    "Post-Harvest":     "violet",
}


def generate_calendar_events(
    crop: str,
    sow_date: date,
) -> list[dict]:
    """
    Generate a list of calendar events from the DAS schedule table.
    Returns list of dicts ready for DB insertion.
    """
    schedule = CROP_SCHEDULES.get(crop, DEFAULT_SCHEDULE)
    events = []
    for das, event_type, title, description in schedule:
        event_date = sow_date + timedelta(days=das)
        events.append({
            "event_type":     event_type,
            "title":          title,
            "description":    description,
            "scheduled_date": event_date,
            "das":            das,
            "is_completed":   False,
        })
    return events
